# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-hits']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_set',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='review.Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_post_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
