# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170807_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='review/post'),
        ),
    ]
