# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20170809_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name_id',
            field=models.ForeignKey(db_column='likeuser', default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
