# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0001_initial'),
        ('review', '0006_post_like_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerNote',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment')),
                ('summer_field', django_summernote.fields.SummernoteTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_summernote.attachment',),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default='', verbose_name='내용'),
        ),
    ]
